// The Electrobun project a `desktop` run builds on the fly.
//
// Nothing here is kept: the project is generated inside the application's build
// directory every time, from the application's own config and the bundle the
// compiler just produced. That is what makes `desktop` a way of *running* an
// application rather than a thing an application has to be — a mosaic app has a
// `main.js`, a page and an `info.json`, and none of them know that Electrobun
// exists.
//
// The one thing an application may say about the desktop is what its native
// side does, in a `bun/` beside `main.js`. By convention that directory is the
// Electrobun main process, so the compiler skips it — it is not browser code
// and it never belongs in the bundle — and this module points Electrobun's
// `bun` entrypoint at it. An application without one gets `DEFAULT_MAIN`, which
// opens a window onto the page and nothing else.

import * as fs from "node:fs";
import * as path from "node:path";

/** The directory holding the native side, beside `main.js`. By convention. */
export const BUN_DIR = "bun";
/**
 * Where the generated project goes, inside the application's build directory.
 *
 * A compile replaces that directory whole, and this is the one thing in it a
 * compile did not produce and must not discard: the dependencies installed
 * here are an application's, not a build's, and reinstalling them because a
 * `.ib.xml` changed would make every rebuild a download.
 */
export const DESKTOP_DIR = "desktop";
/**
 * The toolkit `desktop` builds on, pinned here because this is the only place
 * that knows or cares. An application never names it: `desktop` installs it
 * into the project it generates, the way the compiler vendors the runtime.
 */
const ELECTROBUN_VERSION = "1.18.1";
/** The module Electrobun runs as its main process, inside `BUN_DIR`. */
export const BUN_ENTRY = "index.js";
/** What Electrobun calls the view this generates. Fixed: there is one page. */
const VIEW = "mainview";
/**
 * Electrobun reads this filename and no other — the extension is not a claim
 * about the language, and what is written into it below is plain JavaScript.
 */
const CONFIG = "electrobun.config.ts";

/**
 * The main process an application gets when it does not ship a `bun/`.
 *
 * One window onto the page. An application that wants menus, a tray, a second
 * window or anything else native writes its own and this is never used.
 */
const DEFAULT_MAIN = `// Generated by \`mosaic desktop\`. Written fresh on every run — to change what
// the native side does, put your own \`index.js\` in a \`bun/\` beside main.js
// and mosaic will use that instead of this.
import { BrowserWindow } from "electrobun/bun";

new BrowserWindow({
  title: {{TITLE}},
  url: "views://${VIEW}/index.html",
  frame: { width: 1024, height: 768, x: 200, y: 200 },
});
`;

/** The page an application gets when it does not ship an `index.html`. */
const DEFAULT_PAGE = `<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{{TITLE}}</title>
    <style>
      html, body { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; }
      #app { width: 100%; height: 100%; }
    </style>
  </head>

  <body>
    <div id="app"></div>
    <script type="module" src="app.js"></script>
  </body>
</html>
`;

/** A bundle identifier from an application's name, when it does not name one. */
function identifierFor(name) {
  const slug =
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "app";
  return `com.mosaic.${slug}`;
}

/** How Electrobun should refer to `target` from the generated project. */
function from(dir, target) {
  return path.relative(dir, target).split(path.sep).join("/");
}

/**
 * The application's page, rewritten for the bundle it will sit in.
 *
 * A mosaic page loads `build/app.js`, because that is where the bundle is
 * relative to the application directory it is served from. Electrobun copies
 * the page and the bundle into one directory, so the path that was right for
 * the served app is wrong here and the reference has to move with it. The
 * application's own file is not touched: what is rewritten is this run's copy.
 */
function pageFor(source, outfileName, title) {
  if (!source) return DEFAULT_PAGE.split("{{TITLE}}").join(title);

  const html = fs.readFileSync(source, "utf8");
  // Only a reference to this application's own bundle is rewritten, wherever
  // it sits in the tree — `build/app.js`, `./build/app.js`, `../build/app.js`.
  return html.replace(
    /(["'])((?:\.{1,2}\/)*)[^"']*\/?app\.js\1/g,
    (match, quote) =>
      match.includes(outfileName) || match.endsWith(`/app.js${quote}`)
        ? `${quote}app.js${quote}`
        : match,
  );
}

/**
 * Write the Electrobun project for `app` and return where it went.
 *
 * @param app     the layout a command is running against: `sourceRoot`,
 *                `outdir`, `outfile`, and the `bunDir` convention.
 * @param config  the application's `info.json`, merged.
 * @param dir     where to write the project.
 */
export function writeProject({ app, config, dir }) {
  // Only what this generates is cleared. `node_modules` and the lockfile beside
  // it are this project's too, and reinstalling them on every run would make
  // starting an app a minute's work instead of a moment's.
  fs.mkdirSync(dir, { recursive: true });
  for (const name of [CONFIG, "index.html", BUN_DIR]) {
    fs.rmSync(path.join(dir, name), { recursive: true, force: true });
  }

  const title = config.app_name ?? app.name;
  const identifier = config.identifier || identifierFor(title);

  // The native side is copied in rather than pointed at, so that every module
  // the main process imports resolves against this project's `node_modules` —
  // the one holding what `dependencies` in the application's info.json asked
  // for. A `bun/` is self-contained for the same reason: it is copied whole,
  // and a relative import reaching up out of it would not survive the move.
  const bunDir = path.join(dir, BUN_DIR);
  const bunEntry = path.join(bunDir, BUN_ENTRY);
  const ownMain = path.join(app.bunDir, BUN_ENTRY);
  const ownMainExists = fs.existsSync(ownMain);
  if (ownMainExists) {
    fs.cpSync(app.bunDir, bunDir, { recursive: true });
  } else {
    fs.mkdirSync(bunDir, { recursive: true });
    fs.writeFileSync(
      bunEntry,
      DEFAULT_MAIN.split("{{TITLE}}").join(JSON.stringify(title)),
    );
  }

  // The page, beside the bundle it loads, with its reference to that bundle
  // corrected for the directory Electrobun will put the two of them in.
  const ownPage = [
    path.join(app.sourceRoot, "index.html"),
    path.join(app.source, "index.html"),
  ].find((p) => fs.existsSync(p));
  const page = path.join(dir, "index.html");
  fs.writeFileSync(
    page,
    pageFor(ownPage, path.basename(app.outfile), title),
  );

  const electrobun = {
    app: { name: title, identifier, version: config.version },
    build: {
      views: { [VIEW]: { entrypoint: from(dir, app.outfile) } },
      copy: { [from(dir, page)]: `views/${VIEW}/index.html` },
      bun: { entrypoint: from(dir, bunEntry) },
      // The system webview. Bundling Chromium is a several-hundred-megabyte
      // decision and not one to make on an application's behalf.
      mac: { bundleCEF: false },
      linux: { bundleCEF: false },
      win: { bundleCEF: false },
    },
  };

  fs.writeFileSync(
    path.join(dir, CONFIG),
    `// Generated by \`mosaic desktop\`. Written fresh on every run — edits here\n` +
      `// are lost. What it is generated from is the application's info.json.\n` +
      `export default ${JSON.stringify(electrobun, null, 2)};\n`,
  );

  // What the project installs: the application's own dependencies, and
  // Electrobun.
  //
  // Electrobun is not one of them and is not named in any info.json. It is what
  // `desktop` is *made of* — the same kind of thing as the runtime the compiler
  // vendors — and an application that says it is a desktop app has said
  // everything it needs to about that. Nobody should have to know the name of
  // the window toolkit, or keep its version current, to open a window.
  const declared = { ...(config.dependencies ?? {}) };
  const manifest = {
    name: identifierFor(title).split(".").pop(),
    version: config.version,
    private: true,
    dependencies: { ...declared, electrobun: ELECTROBUN_VERSION },
  };
  const manifestFile = path.join(dir, "package.json");
  const wanted = `${JSON.stringify(manifest, null, 2)}\n`;
  const had = fs.existsSync(manifestFile)
    ? fs.readFileSync(manifestFile, "utf8")
    : null;
  if (had !== wanted) fs.writeFileSync(manifestFile, wanted);

  return {
    dir,
    page,
    bunEntry,
    ownMain: ownMainExists,
    // What the application asked for, which is what there is any point telling
    // it about. Electrobun going in alongside is not news.
    dependencies: declared,
    // Whether an install is owed: the list changed, or there is nothing
    // installed to satisfy the one already written.
    needsInstall:
      had !== wanted || !fs.existsSync(path.join(dir, "node_modules")),
  };
}

/**
 * Install the project's dependencies, if it is owed an install.
 *
 * They land in the generated project rather than in the application, which is
 * what keeps an application's own directory to the things its author wrote:
 * `info.json` says what is needed, and the build directory is where the needing
 * is done. Deleting the build directory therefore costs an install and nothing
 * else.
 */
export async function installDependencies({ dir, needsInstall, log }) {
  if (!needsInstall) return true;

  const bun = Bun.which("bun");
  if (!bun) {
    throw new Error(
      "`desktop` installs the app's dependencies with bun, and bun is not on " +
        "PATH.\n    Install it from https://bun.sh.",
    );
  }

  log?.("==> installing dependencies");
  const proc = Bun.spawn([bun, "install"], {
    cwd: dir,
    stdout: "inherit",
    stderr: "inherit",
  });
  if ((await proc.exited) !== 0) {
    throw new Error(`\`bun install\` failed in ${dir}`);
  }
  return true;
}

/**
 * Electrobun's CLI, as installed for this application.
 *
 * It is the application's dependency and not mosaic's: mosaic compiles the
 * page, and an application that wants to be a desktop app says so by depending
 * on the thing that makes it one. Looked for the way a module resolver would,
 * so it is found wherever in the project it was installed.
 */
export function findElectrobun(start) {
  let dir = path.resolve(start);
  for (;;) {
    const bin = path.join(dir, "node_modules", ".bin", "electrobun");
    if (fs.existsSync(bin)) return bin;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}
