// The Electrobun project a `desktop` run builds on the fly.
//
// Nothing here is kept: the project is generated inside the application's build
// directory every time, from the application's own config and the bundle the
// compiler just produced. That is what makes `desktop` a way of *running* an
// application rather than a thing an application has to be — a mosaic app has a
// `main.js`, a page and an `info.json`, and none of them know that Electrobun
// exists.
//
// The main process is generated with the rest of it. An application does not
// write one: what would vary between two of them is a title and a window size,
// and both are in `info.json`.
//
// What an application does put in the `bun/` beside `main.js` is services — the
// modules a page calls. The compiler skips that directory, since none of it is
// browser code and none of it belongs in the bundle, and a service names
// neither Electrobun nor rpc, which is what lets the same file answer over the
// desktop bridge here and over HTTP under `mosaic web`.

import * as fs from "node:fs";
import * as path from "node:path";

import { findServices, registrySource } from "../../frameworks/rpc/services.js";

/** The directory holding the native side, beside `main.js`. By convention. */
export const BUN_DIR = "bun";
/**
 * Where the generated project goes, inside the application's build directory.
 *
 * A compile replaces that directory whole, and this is the one thing in it a
 * compile did not produce and must not discard: the dependencies installed
 * here are an application's, not a build's, and reinstalling them because a
 * `.ib.xml` changed would make every rebuild a download.
 */
export const DESKTOP_DIR = "desktop";
/**
 * The toolkit `desktop` builds on, pinned here because this is the only place
 * that knows or cares. An application never names it: `desktop` installs it
 * into the project it generates, the way the compiler vendors the runtime.
 */
const ELECTROBUN_VERSION = "1.18.1";
/** The module Electrobun runs as its main process, inside `BUN_DIR`. */
export const BUN_ENTRY = "index.js";
/** What Electrobun calls the view this generates. Fixed: there is one page. */
const VIEW = "mainview";
/**
 * Electrobun reads this filename and no other — the extension is not a claim
 * about the language, and what is written into it below is plain JavaScript.
 */
const CONFIG = "electrobun.config.ts";

/**
 * The main process. Always generated, never an application's to write.
 *
 * Opening a window is not what an application is about, and every application
 * that did it wrote the same six lines — naming Electrobun, naming the view
 * `desktop` had generated for it, and wiring up an rpc bridge whose whole
 * definition is elsewhere. Getting any of it wrong broke the app, and getting
 * it right taught the author nothing about their own program.
 *
 * So `bun/` holds services and nothing else. A service is a plain module that
 * knows about neither Electrobun nor rpc, which is what lets the same file
 * answer over the desktop bridge and over HTTP under `mosaic web`.
 *
 * What varies between applications comes from `info.json`, which is where an
 * application says everything else about itself.
 */
const MAIN = `// The window.
import { BrowserWindow } from "electrobun/bun";

new BrowserWindow({
  title: {{TITLE}},
  url: "views://${VIEW}/index.html",
  frame: {{FRAME}},
  // What lets the page call the application's services. An app with none has
  // a \`mosaicRpc\` that answers nothing, so this is the same line either way.
  rpc: globalThis.mosaicRpc?.(),
});
`;

/**
 * The one banner the generated entrypoint carries, whatever it is made of.
 */
const BANNER = `// Generated by \`mosaic desktop\`. Written fresh on every run — edits here are
// lost, and there is nothing here to edit: the title and the window come from
// info.json, and the services come from the modules in \`services/\`.
`;

/** The window an application asks for, over the one it gets by default. */
const DEFAULT_FRAME = { width: 1024, height: 768, x: 200, y: 200 };

/** The page an application gets when it does not ship an `index.html`. */
const DEFAULT_PAGE = `<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{{TITLE}}</title>
    <style>
      html, body { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; }
      #app { width: 100%; height: 100%; }
    </style>
  </head>

  <body>
    <div id="app"></div>
    <script type="module" src="app.js"></script>
  </body>
</html>
`;

/** A bundle identifier from an application's name, when it does not name one. */
function identifierFor(name) {
  const slug =
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "app";
  return `com.mosaic.${slug}`;
}

/** How Electrobun should refer to `target` from the generated project. */
function from(dir, target) {
  return path.relative(dir, target).split(path.sep).join("/");
}

/**
 * The application's page, rewritten for the bundle it will sit in.
 *
 * A mosaic page loads `build/app.js`, because that is where the bundle is
 * relative to the application directory it is served from. Electrobun copies
 * the page and the bundle into one directory, so the path that was right for
 * the served app is wrong here and the reference has to move with it. The
 * application's own file is not touched: what is rewritten is this run's copy.
 */
function pageFor(source, outfileName, title) {
  if (!source) return DEFAULT_PAGE.split("{{TITLE}}").join(title);

  const html = fs.readFileSync(source, "utf8");
  // Only a reference to this application's own bundle is rewritten, wherever
  // it sits in the tree — `build/app.js`, `./build/app.js`, `../build/app.js`.
  return html.replace(
    /(["'])((?:\.{1,2}\/)*)[^"']*\/?app\.js\1/g,
    (match, quote) =>
      match.includes(outfileName) || match.endsWith(`/app.js${quote}`)
        ? `${quote}app.js${quote}`
        : match,
  );
}

/** The one Electrobun rpc method every mosaic call travels on. */
export const RPC_METHOD = "mosaic.rpc";

/** Where the copied dispatcher and the generated registry sit, inside `bun/`. */
const RPC_DIR = "_mosaic";

/**
 * What the main process runs so a page can call the application's services.
 *
 * Generated rather than asked of the author, because the two ends have to
 * agree and only one of them is anybody's code: the services are the
 * application's, the bridge is Electrobun's, and this is the strip between
 * them.
 *
 * It is written above the window rather than into a module of its own, and the
 * two are one file: Electrobun's launcher runs `bun/index.js` and no other name
 * — an entrypoint called anything else is bundled under that name and then
 * never found, which is a window that silently fails to open.
 */
const RPC_PREAMBLE = `// The page calls a service by name and this answers, running the same
// dispatcher \`mosaic web\` runs behind its POST. A service therefore behaves
// the same whichever host an application is under, which is the one property
// worth having here.
import { BrowserView } from "electrobun/bun";

import { dispatch } from "./${RPC_DIR}/dispatch.js";
import services from "./${RPC_DIR}/services.js";

/**
 * The rpc to hand a window:
 *
 *   new BrowserWindow({ …, rpc: mosaicRpc() });
 *
 * A global rather than an import, so that the window below needs no path to a
 * module that exists only once this project has been generated. It is defined
 * before that window is made, which is the ordering everything here rests on.
 *
 * Every mosaic call travels on one Electrobun method: what is being called is
 * in the message, so a service is reached by exporting a function and nothing
 * has to be registered here.
 */
globalThis.mosaicRpc = (window = null) =>
  BrowserView.defineRPC({
    maxRequestTime: 0,
    handlers: {
      requests: {
        ${JSON.stringify(RPC_METHOD)}: (message) =>
          dispatch(message, services, { window, host: "desktop" }),
      },
      messages: {},
    },
  });
`;

/**
 * Write the Electrobun project for `app` and return where it went.
 *
 * @param app     the layout a command is running against: `sourceRoot`,
 *                `outdir`, `outfile`, and the `bunDir` convention.
 * @param config  the application's `info.json`, merged.
 * @param dir     where to write the project.
 */
export function writeProject({ app, config, dir }) {
  // Only what this generates is cleared. `node_modules` and the lockfile beside
  // it are this project's too, and reinstalling them on every run would make
  // starting an app a minute's work instead of a moment's.
  fs.mkdirSync(dir, { recursive: true });
  for (const name of [CONFIG, "index.html", BUN_DIR]) {
    fs.rmSync(path.join(dir, name), { recursive: true, force: true });
  }

  const title = config.app_name ?? app.name;
  const identifier = config.identifier || identifierFor(title);

  // The native side is copied in rather than pointed at, so that every module
  // the main process imports resolves against this project's `node_modules` —
  // the one holding what `dependencies` in the application's info.json asked
  // for. A `bun/` is self-contained for the same reason: it is copied whole,
  // and a relative import reaching up out of it would not survive the move.
  const bunDir = path.join(dir, BUN_DIR);
  const bunEntry = path.join(bunDir, BUN_ENTRY);

  // The application's `bun/` comes over whole — the services and whatever they
  // are built out of. What it does not bring is a main process: that is written
  // here, over anything of that name, because it is generated and an
  // application has no business keeping a copy of it.
  if (fs.existsSync(app.bunDir)) {
    fs.cpSync(app.bunDir, bunDir, { recursive: true });
  } else {
    fs.mkdirSync(bunDir, { recursive: true });
  }

  // The page, beside the bundle it loads, with its reference to that bundle
  // corrected for the directory Electrobun will put the two of them in.
  const ownPage = [
    path.join(app.sourceRoot, "index.html"),
    path.join(app.source, "index.html"),
  ].find((p) => fs.existsSync(p));
  const page = path.join(dir, "index.html");
  fs.writeFileSync(
    page,
    pageFor(ownPage, path.basename(app.outfile), title),
  );

  // The services, and the glue that answers a page's calls with them. Written
  // into the copy rather than into the application: it is derived from what
  // the application already says, and a generated file in a source tree is a
  // file someone will edit.
  //
  // Found in the copy rather than in the source tree, so the registry's
  // imports are its neighbours: this project is what Electrobun bundles, and
  // an import reaching back out of it would tie the packaged app to the
  // machine it was built on.
  const services = findServices(bunDir);
  let preamble = "";
  if (services.length > 0) {
    const rpcDir = path.join(bunDir, RPC_DIR);
    fs.mkdirSync(rpcDir, { recursive: true });

    // The dispatcher is copied rather than imported: Electrobun bundles this
    // project from its bun entrypoint, and mosaic is not one of the project's
    // dependencies — nor should it be, since what is needed is one file.
    //
    // Found through `runtimeRoot`, the way every other tree mosaic ships is,
    // and not through this file's own directory: a compiled `mosaic` has no
    // directory to speak of, and the frameworks are installed beside the binary
    // rather than inside it.
    fs.copyFileSync(
      path.join(config.runtimeRoot, "..", "frameworks", "rpc", "dispatch.js"),
      path.join(rpcDir, "dispatch.js"),
    );
    fs.writeFileSync(
      path.join(rpcDir, "services.js"),
      registrySource(services, rpcDir),
    );

    preamble = `${RPC_PREAMBLE}\n`;
  }

  // One file, and it is `index.js`.
  //
  // Electrobun's launcher runs `app/bun/index.js` by that name and no other,
  // while its bundler names the output after whatever entrypoint it was given.
  // An entrypoint called anything else is therefore built and then never run:
  // the app starts, the launcher finds nothing to run, and no window opens with
  // nothing said about why. Only applications with services ever hit it, which
  // is why every example without them worked.
  const frame = { ...DEFAULT_FRAME, ...(config.window ?? {}) };
  fs.writeFileSync(
    bunEntry,
    BANNER +
      "\n" +
      preamble +
      MAIN.split("{{TITLE}}")
        .join(JSON.stringify(title))
        .split("{{FRAME}}")
        .join(JSON.stringify(frame)),
  );
  const entry = bunEntry;

  const electrobun = {
    app: { name: title, identifier, version: config.version },
    build: {
      views: { [VIEW]: { entrypoint: from(dir, app.outfile) } },
      copy: { [from(dir, page)]: `views/${VIEW}/index.html` },
      bun: { entrypoint: from(dir, entry) },
      // The system webview. Bundling Chromium is a several-hundred-megabyte
      // decision and not one to make on an application's behalf.
      mac: { bundleCEF: false },
      linux: { bundleCEF: false },
      win: { bundleCEF: false },
    },
  };

  fs.writeFileSync(
    path.join(dir, CONFIG),
    `// Generated by \`mosaic desktop\`. Written fresh on every run — edits here\n` +
      `// are lost. What it is generated from is the application's info.json.\n` +
      `export default ${JSON.stringify(electrobun, null, 2)};\n`,
  );

  // What the project installs: the application's own dependencies, and
  // Electrobun.
  //
  // Electrobun is not one of them and is not named in any info.json. It is what
  // `desktop` is *made of* — the same kind of thing as the runtime the compiler
  // vendors — and an application that says it is a desktop app has said
  // everything it needs to about that. Nobody should have to know the name of
  // the window toolkit, or keep its version current, to open a window.
  const declared = { ...(config.dependencies ?? {}) };
  const manifest = {
    name: identifierFor(title).split(".").pop(),
    version: config.version,
    private: true,
    dependencies: { ...declared, electrobun: ELECTROBUN_VERSION },
  };
  const manifestFile = path.join(dir, "package.json");
  const wanted = `${JSON.stringify(manifest, null, 2)}\n`;
  const had = fs.existsSync(manifestFile)
    ? fs.readFileSync(manifestFile, "utf8")
    : null;
  if (had !== wanted) fs.writeFileSync(manifestFile, wanted);

  return {
    dir,
    page,
    bunEntry: entry,
    /** The groups a page can call, for the command to report. */
    services: services.map(({ group }) => group),
    // What the application asked for, which is what there is any point telling
    // it about. Electrobun going in alongside is not news.
    dependencies: declared,
    // Whether an install is owed: the list changed, or there is nothing
    // installed to satisfy the one already written.
    needsInstall:
      had !== wanted || !fs.existsSync(path.join(dir, "node_modules")),
  };
}

/**
 * Install the project's dependencies, if it is owed an install.
 *
 * They land in the generated project rather than in the application, which is
 * what keeps an application's own directory to the things its author wrote:
 * `info.json` says what is needed, and the build directory is where the needing
 * is done. Deleting the build directory therefore costs an install and nothing
 * else.
 */
export async function installDependencies({ dir, needsInstall, log }) {
  if (!needsInstall) return true;

  const bun = Bun.which("bun");
  if (!bun) {
    throw new Error(
      "`desktop` installs the app's dependencies with bun, and bun is not on " +
        "PATH.\n    Install it from https://bun.sh.",
    );
  }

  log?.("==> installing dependencies");
  const proc = Bun.spawn([bun, "install"], {
    cwd: dir,
    stdout: "inherit",
    stderr: "inherit",
  });
  if ((await proc.exited) !== 0) {
    throw new Error(`\`bun install\` failed in ${dir}`);
  }
  return true;
}

/**
 * Electrobun's CLI, as installed for this application.
 *
 * It is the application's dependency and not mosaic's: mosaic compiles the
 * page, and an application that wants to be a desktop app says so by depending
 * on the thing that makes it one. Looked for the way a module resolver would,
 * so it is found wherever in the project it was installed.
 */
export function findElectrobun(start) {
  let dir = path.resolve(start);
  for (;;) {
    const bin = path.join(dir, "node_modules", ".bin", "electrobun");
    if (fs.existsSync(bin)) return bin;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}
