// Finding an application's services, and writing the module that imports them.
//
// A service is a module in `bun/services/` beside the native side, and its file
// name is the group a page calls it by: `notes.js` answers `api.notes.*`. That
// is the whole convention — there is no registry to keep, and adding a service
// is adding a file.
//
// Why a *generated* module rather than reading the directory at run time: the
// desktop bundles its Bun side from one entry point, and a bundler cannot see
// an import whose path is worked out while the program runs. A directory scan
// would work perfectly under `mosaic web` and silently ship nothing at all in
// the packaged app — the worst shape a difference between two hosts can take.
// So the scan happens once, here, at build time, and what both hosts load is a
// module of plain static imports.
import * as fs from "node:fs";
import * as path from "node:path";

/** The directory holding an application's services, inside its `bun/`. */
export const SERVICES_DIR = "services";

/** What a group may be called: a name a page can write after `api.`. */
const GROUP = /^[A-Za-z_$][\w$]*$/;

/**
 * The services an application has, in the order a page would read them.
 *
 * @param {string} bunDir The application's `bun/` directory.
 * @returns {Array<{group: string, file: string}>} empty for an application
 *   with no services, which is most of them.
 */
export function findServices(bunDir) {
  const dir = path.join(bunDir, SERVICES_DIR);
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return [];

  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /\.m?js$/.test(entry.name))
    // `index.js` is a module that gathers others rather than a service of its
    // own, and a leading `_` is the usual way of saying "not for anyone else".
    .filter((entry) => !entry.name.startsWith("_") && entry.name !== "index.js")
    .map((entry) => ({
      group: entry.name.replace(/\.m?js$/, ""),
      file: path.join(dir, entry.name),
    }))
    .filter(({ group }) => GROUP.test(group))
    .sort((a, b) => a.group.localeCompare(b.group));
}

/**
 * The module that imports them all and hands them over as one object.
 *
 * Written into the build rather than into the application: it is derived from
 * what the application already says, and a generated file in a source tree is
 * a file someone will edit.
 *
 * @param {Array<{group: string, file: string}>} services
 * @param {string} from Where the module will sit, for the relative imports.
 * @returns {string} the module's source.
 */
export function registrySource(services, from) {
  const specifier = (file) => {
    const rel = path.relative(from, file).split(path.sep).join("/");
    return rel.startsWith(".") ? rel : `./${rel}`;
  };

  const imports = services
    .map(({ group, file }) => `import ${group} from ${JSON.stringify(specifier(file))};`)
    .join("\n");

  const listed = services.map(({ group }) => `  ${group},`).join("\n");

  return (
    `// Generated by mosaic. Written fresh on every build — edits here are lost.\n` +
    `//\n` +
    `// The application's services, gathered from bun/${SERVICES_DIR}/. The imports\n` +
    `// are static because the desktop's Bun side is bundled from one entry, and a\n` +
    `// bundler cannot follow an import worked out at run time.\n` +
    (imports ? `${imports}\n\n` : `\n`) +
    `export default {\n${listed}${listed ? "\n" : ""}};\n`
  );
}
