//! Combines the compiled modules into one payload with a source map.
//!
//! Each compiled module imports the runtime and, for `.ib` pages, its child
//! components. Bundling hoists a single runtime import, drops the internal ones
//! (the modules are now neighbours in one scope), and re-exports the entry
//! component as the payload's default.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

/// One compiled module on its way into the bundle.
pub struct Module {
    /// Original source file, recorded in the source map.
    pub source: PathBuf,
    /// Original source text, inlined into the source map.
    pub source_text: String,
    /// Generated code, markers already stripped.
    pub code: String,
    /// `(generated line, source line)`, both 1-based.
    pub mappings: Vec<(usize, usize)>,
    /// Exported component name, e.g. `Counter`.
    pub name: String,
}

pub struct Bundle {
    pub code: String,
    pub map: String,
}

/// Build the payload. `entry` names the component the bundle default-exports.
pub fn bundle(
    modules: Vec<Module>,
    runtime: &str,
    entry: &str,
    map_name: &str,
    base: &Path,
) -> Result<Bundle, String> {
    let ordered = order_by_dependency(modules);

    let mut runtime_names: Vec<String> = Vec::new();
    let mut bodies: Vec<(&Module, String, Vec<(usize, usize)>)> = Vec::new();

    let bundled: Vec<String> = ordered.iter().map(|m| m.name.clone()).collect();

    for module in &ordered {
        let (body, names, line_map) = strip_module_syntax(&module.code, runtime, &bundled);
        for name in names {
            if !runtime_names.contains(&name) {
                runtime_names.push(name);
            }
        }
        let shifted = shift_mappings(&line_map, &module.mappings);
        bodies.push((module, body, shifted));
    }

    let mut code = String::new();
    code.push_str(&format!(
        "// Generated by ibcompile — do not edit.\nimport {{ {} }} from {};\n\n",
        runtime_names.join(", "),
        quote(runtime)
    ));

    let mut line = code.matches('\n').count() + 1;
    let mut sources: Vec<String> = Vec::new();
    let mut contents: Vec<String> = Vec::new();
    let mut segments: Vec<(usize, usize, usize)> = Vec::new(); // (gen line, src idx, src line)

    for (module, body, mappings) in &bodies {
        let index = sources.len();
        sources.push(relative(&module.source, base));
        contents.push(module.source_text.clone());

        code.push_str(&format!("// --- {} ---\n", sources[index]));
        line += 1;

        for (gen, src) in mappings {
            segments.push((line + gen - 1, index, *src));
        }

        code.push_str(body);
        if !body.ends_with('\n') {
            code.push('\n');
        }
        code.push('\n');
        line += body.matches('\n').count() + if body.ends_with('\n') { 1 } else { 2 };
    }

    if !ordered.iter().any(|m| m.name == entry) {
        return Err(format!(
            "no entry component named `{}` — expected a main.ib or Main.js",
            entry
        ));
    }
    code.push_str(&format!("export default {};\n", entry));
    code.push_str(&format!("//# sourceMappingURL={}\n", map_name));

    let map = source_map(&sources, &contents, &segments);
    Ok(Bundle { code, map })
}

/// Remove `import`/`export default` syntax, returning the body, the runtime
/// names the module used, and where each original line ended up (`None` when
/// the line was dropped). Import lines sit in the middle of a file as often as
/// at the top, so the shift is tracked per line rather than as one offset.
fn strip_module_syntax(
    code: &str,
    runtime: &str,
    bundled: &[String],
) -> (String, Vec<String>, Vec<Option<usize>>) {
    let mut out = String::new();
    let mut names: Vec<String> = Vec::new();
    let mut line_map: Vec<Option<usize>> = vec![None]; // index 0 unused
    let mut kept = 1usize;

    for line in code.split_inclusive('\n') {
        let trimmed = line.trim();

        if trimmed.starts_with("import ") {
            // The runtime import contributes its names to the hoisted one.
            if trimmed.contains(runtime) {
                if let (Some(open), Some(close)) = (trimmed.find('{'), trimmed.find('}')) {
                    for name in trimmed[open + 1..close].split(',') {
                        let name = name.trim().to_string();
                        if !name.is_empty() && !names.contains(&name) {
                            names.push(name);
                        }
                    }
                }
                line_map.push(None);
                continue;
            }

            // An import of another bundled module disappears — they share one
            // scope now. An import of anything else (a component library
            // compiled separately, say) has to stay, or its binding is lost.
            if bundled.iter().any(|n| trimmed.contains(&format!("/{}.js", n))
                || trimmed.contains(&format!("\"./{}.js", n))
                || trimmed.contains(&format!("'./{}.js", n)))
            {
                line_map.push(None);
                continue;
            }

            out.push_str(line);
            line_map.push(Some(kept));
            kept += 1;
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("export default ") {
            out.push_str(rest);
            if line.ends_with('\n') {
                out.push('\n');
            }
            line_map.push(Some(kept));
            kept += 1;
            continue;
        }

        out.push_str(line);
        line_map.push(Some(kept));
        kept += 1;
    }

    // Leading blank lines left behind by removed imports are trimmed too.
    let trimmed_out = out.trim_start_matches('\n').to_string();
    let dropped_blanks = out.len() - trimmed_out.len();
    if dropped_blanks > 0 {
        for slot in line_map.iter_mut() {
            if let Some(n) = slot {
                *n = n.saturating_sub(dropped_blanks);
            }
        }
    }

    (trimmed_out, names, line_map)
}

/// Recompute generated line numbers using the per-line map from stripping.
fn shift_mappings(line_map: &[Option<usize>], mappings: &[(usize, usize)]) -> Vec<(usize, usize)> {
    mappings
        .iter()
        .filter_map(|(gen, src)| {
            line_map
                .get(*gen)
                .copied()
                .flatten()
                .map(|new_line| (new_line, *src))
        })
        .collect()
}

/// Dependency order: a page that renders `<Counter/>` comes after Counter.
fn order_by_dependency(modules: Vec<Module>) -> Vec<Module> {
    let names: Vec<String> = modules.iter().map(|m| m.name.clone()).collect();
    let mut placed: HashSet<String> = HashSet::new();
    let mut out: Vec<Module> = Vec::new();
    let mut pending: Vec<Module> = modules;

    // Small graphs, so a simple repeated sweep is clearer than a real toposort.
    while !pending.is_empty() {
        let before = pending.len();
        let mut still: Vec<Module> = Vec::new();

        for module in pending {
            let ready = names.iter().all(|dep| {
                *dep == module.name || placed.contains(dep) || !imports(&module.code, dep)
            });
            if ready {
                placed.insert(module.name.clone());
                out.push(module);
            } else {
                still.push(module);
            }
        }

        pending = still;
        if pending.len() == before {
            // A cycle: emit the rest in input order rather than looping forever.
            out.append(&mut pending);
            break;
        }
    }
    out
}

fn imports(code: &str, name: &str) -> bool {
    code.lines().any(|l| {
        let t = l.trim();
        t.starts_with("import ") && t.contains(&format!("./{}.js", name))
    })
}

fn relative(path: &Path, base: &Path) -> String {
    path.strip_prefix(base)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

/// A v3 source map with line-level mappings and inlined sources.
fn source_map(sources: &[String], contents: &[String], segments: &[(usize, usize, usize)]) -> String {
    let mut by_line: Vec<(usize, usize, usize)> = segments.to_vec();
    by_line.sort_by_key(|(gen, _, _)| *gen);
    by_line.dedup_by_key(|(gen, _, _)| *gen);

    let mut mappings = String::new();
    let mut current_line = 1usize;
    let mut prev_source = 0i64;
    let mut prev_source_line = 0i64;

    for (gen, source, src_line) in by_line {
        while current_line < gen {
            mappings.push(';');
            current_line += 1;
        }
        // Each mapped line gets one segment: generated column 0 -> source line.
        let mut segment = String::new();
        segment.push_str(&vlq(0));
        segment.push_str(&vlq(source as i64 - prev_source));
        segment.push_str(&vlq(src_line as i64 - 1 - prev_source_line));
        segment.push_str(&vlq(0));
        prev_source = source as i64;
        prev_source_line = src_line as i64 - 1;

        mappings.push_str(&segment);
        mappings.push(';');
        current_line += 1;
    }

    let sources_json = sources
        .iter()
        .map(|s| quote(s))
        .collect::<Vec<_>>()
        .join(", ");
    let contents_json = contents
        .iter()
        .map(|c| json_string(c))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        "{{\"version\": 3, \"sources\": [{}], \"sourcesContent\": [{}], \"names\": [], \"mappings\": {}}}\n",
        sources_json,
        contents_json,
        json_string(&mappings)
    )
}

fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Base64 VLQ, as source maps encode their numbers.
fn vlq(value: i64) -> String {
    const ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut v = if value < 0 {
        ((-value) << 1) | 1
    } else {
        value << 1
    };
    let mut out = String::new();
    loop {
        let mut digit = v & 0b11111;
        v >>= 5;
        if v > 0 {
            digit |= 0b100000;
        }
        out.push(ALPHABET[digit as usize] as char);
        if v == 0 {
            break;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn module(name: &str, code: &str) -> Module {
        Module {
            source: PathBuf::from(format!("examples/{}.ib", name)),
            source_text: "source".into(),
            code: code.into(),
            mappings: vec![(1, 1)],
            name: name.into(),
        }
    }

    #[test]
    fn vlq_encodes_like_the_spec() {
        assert_eq!(vlq(0), "A");
        assert_eq!(vlq(1), "C");
        assert_eq!(vlq(-1), "D");
        assert_eq!(vlq(16), "gB");
    }

    #[test]
    fn imports_are_hoisted_and_deduplicated() {
        let a = module(
            "Counter",
            "import { h, View } from \"./mosaic.js\";\nexport default class Counter {}\n",
        );
        let b = module(
            "Main",
            "import { h, bindText } from \"./mosaic.js\";\nimport Counter from \"./Counter.js\";\nexport default function Main() {}\n",
        );
        let out = bundle(vec![b, a], "./mosaic.js", "Main", "app.js.map", Path::new(".")).unwrap();

        assert_eq!(out.code.matches("import").count(), 1, "{}", out.code);
        assert!(out.code.contains("import { h, View, bindText } from \"./mosaic.js\";"), "{}", out.code);
        assert!(!out.code.contains("export default class"), "{}", out.code);
        assert!(out.code.contains("class Counter {}"), "{}", out.code);
        assert!(out.code.trim_end().ends_with("//# sourceMappingURL=app.js.map"), "{}", out.code);
    }

    #[test]
    fn imports_of_modules_outside_the_bundle_are_kept() {
        // build/ui/Button.js is compiled separately; dropping its import would
        // leave `Button` undefined in the payload.
        let m = module(
            "Main",
            "import { h } from \"./mosaic.js\";\nimport Button from \"./ui/Button.js\";\nexport default function Main() {}\n",
        );
        let out = bundle(vec![m], "./mosaic.js", "Main", "m.map", Path::new(".")).unwrap();
        assert!(out.code.contains("import Button from \"./ui/Button.js\";"), "{}", out.code);
        assert_eq!(out.code.matches("import").count(), 2, "{}", out.code);
    }

    #[test]
    fn dependencies_come_first() {
        let main = module(
            "Main",
            "import Counter from \"./Counter.js\";\nexport default function Main() {}\n",
        );
        let counter = module("Counter", "export default class Counter {}\n");
        let out = bundle(vec![main, counter], "./m.js", "Main", "m.map", Path::new(".")).unwrap();

        let counter_at = out.code.find("class Counter").unwrap();
        let main_at = out.code.find("function Main").unwrap();
        assert!(counter_at < main_at, "{}", out.code);
    }

    #[test]
    fn the_entry_is_the_default_export() {
        let out = bundle(
            vec![module("Main", "export default function Main() {}\n")],
            "./m.js",
            "Main",
            "m.map",
            Path::new("."),
        )
        .unwrap();
        assert!(out.code.contains("export default Main;"), "{}", out.code);
    }

    #[test]
    fn a_missing_entry_is_an_error() {
        let out = bundle(
            vec![module("Counter", "export default class Counter {}\n")],
            "./m.js",
            "Main",
            "m.map",
            Path::new("."),
        );
        assert!(out.is_err());
    }

    #[test]
    fn the_map_carries_sources_and_content() {
        let out = bundle(
            vec![module("Main", "export default function Main() {}\n")],
            "./m.js",
            "Main",
            "m.map",
            Path::new("."),
        )
        .unwrap();
        assert!(out.map.contains("\"version\": 3"), "{}", out.map);
        assert!(out.map.contains("examples/Main.ib"), "{}", out.map);
        assert!(out.map.contains("\"sourcesContent\": [\"source\"]"), "{}", out.map);
    }
}
